### ISSUE TITLE
Test suite on root level won't compile

### ISSUE THREAD

**Issue by marcgrue** [scala-native/scala-native#1647]
Placing a test suite on root level won't compile.

Commands to reproduce:
```
git clone https://github.com/marcgrue/scalajs-cross-compile-example.git
cd scalajs-cross-compile-example
git checkout e021203c5d766e3adb45a1c7b18ae7e548063b7b
sbt
fooNative/test
```
This gives these errors:
```
[error] /Users/mg/Desktop/scalajs-cross-compile-example/native/target/scala-2.11/src_managed/nativetest/FrameworksMap.scala:4:67: object TestNative is not a member of package <root>
[error]   override val tests = Map[String, AnyRef]("TestNative" -> _root_.TestNative, "TestShared" -> _root_.TestShared)
[error]                                                                   ^
[error] /Users/mg/Desktop/scalajs-cross-compile-example/native/target/scala-2.11/src_managed/nativetest/FrameworksMap.scala:4:102: object TestShared is not a member of package <root>
[error]   override val tests = Map[String, AnyRef]("TestNative" -> _root_.TestNative, "TestShared" -> _root_.TestShared)
[error]                                                                                                      ^
```
It's hard to guess that a test suite has to be moved out of root into to any package. It would be nice if having test suites on the root level was allowed. Otherwise a simple message asking to move into a package would be very helpful. This workaround has been [noted before by @xeno-by](https://github.com/scalameta/scalameta/issues/772#issuecomment-362380136)

**Comment by sjrd** [comment]
I think this was fixed in #1727.

**Comment by marcgrue** [comment]
Hm, unfortunately, running the commands above still don't let the SN compile the root level classes. Also tried to upgrade to SN 0.4.0-M2 to no prevail. So I'm afraid the issue remains. Does reproducing the case as shown above pass for you?

**Comment by sjrd** [comment]
This was only fixed in master. It will be part of the next release (I don't know when yet).

**Comment by marcgrue** [comment]
Ah, ok, great thanks!! Fantastic job you and the rest are doing.
