### ISSUE TITLE
Java 9+ add additional Math functions

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#2473]
The most important ones are the `(long x, int y)` ones as they conflict with the existing `(long x, long y)` ones.
```java
public static long multiplyExact​(long x, int y)
public static long multiplyFull​(int x, int y)
public static long multiplyHigh​(long x, long y)
public static long floorDiv​(long x, int y)
public static int floorMod​(long x, int y)
public static double fma​(double a, double b, double c)
public static float fma​(float a, float b, float c)
```

**Comment by plokhotnyuk** [comment]
Also, please add `public static long unsignedMultiplyHigh(long x, long y)` from JDK 19.

Currently jsoniter-scala-core has implementations of `multiplyHigh​` and `unsignedMultiplyHigh` for 64-bit platforms: 
https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-core/native/src/main/resources/scala-native/multiply_high.c

It can be compiled to one mul ops by x86 clang, but for ARM it uses 3 mul ops: https://godbolt.org/z/fcYEbYb8a

Is any possibility to have cross-platform version that uses minimum mul ops for all platform?

How about support of 32-bit architectures?

**Comment by vincenzopalazzo** [comment]
this should be fixed https://github.com/scala-native/scala-native/pull/2990 ?

**Comment by armanbilge** [comment]
@vincenzopalazzo I am afraid not, we are still missing some methods like `multiplyHigh`. PRs welcome! :)

**Comment by plokhotnyuk** [comment]
@WojciechMazur Can be https://github.com/scala-native/scala-native/pull/3480 reimplemented to use just one multiplication on platforms which support that?

I have spot that some projects use `#if defined` switches like [here](https://github.com/fastfloat/fast_float/blob/77cc847c842c49e7e3477c1e95da2b6540166d66/include/fast_float/float_common.h#L398-L409) but I don't know yet if I can reuse the similar approach in the jsoniter-scala project for [custom implementations of `Math.multiplyHigh` and `Math.unsignedMultiplyHigh`](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-core/native/src/main/resources/scala-native/multiply_high.c) to avoid [unexpected errors on Windows](https://github.com/plokhotnyuk/jsoniter-scala/issues/1247).

**Comment by ekrich** [comment]
Closed via https://github.com/scala-native/scala-native/pull/4340, thanks @LeeTibbert
